name: 'automation test'
description: 'Run unit tests'

inputs:
  NODE_VERSION:
    description: 'Node version'
    required: false
    default: '20'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Use Node ${{ inputs.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - name: Install dependencies
      shell: bash
      run: npm install

