name: 'Quality Gate'
description: 'Run quality gate'

inputs:
  SONAR_TOKEN:
    description: 'Sonar Token'
    required: true
  SONAR_HOST:
    description: 'Sonar Host'
    required: true
  WITH_COVERAGE:
    description: 'With coverage'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
  - name: Cleanup runner workspace
      shell: bash
      if: always()
      run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true
        rm -rf $GITHUB_WORKSPACE/*
        
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Download lcov code coverage
    uses: actions/download-artifact@v4
    if: ${{ inputs.WITH_COVERAGE == 'true' }}
    with:
      name: coverage
      path: coverage

  - name: SonarQube Scan
    uses: sonarsource/sonarqube-scan-action@v1.1.0
    env:
      SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ inputs.SONAR_HOST }}

  - name: Quality Gate Check
    uses: sonarsource/sonarqube-quality-gate-action@v1.0.0
    # timeout-minutes: 5 // not supported in composite actions
    env:
      SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
