name: 'Upgrade Rey Common'
description: 'upgrade rey-common version'

inputs:
  VERSION:
    description: 'ArgoCD repository'
    required: false
  PAT:
    description: 'Personal Access Token'
    required: true

runs:
  using: "composite"
  steps:
    - id: latest
      if: ${{ !inputs.VERSION }}
      uses: pozetroninc/github-action-get-latest-release@v0.7.0
      with:
        owner: REY-ID
        repo: rey-common
        excludes: prerelease, draft
        token: ${{ inputs.PAT }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ inputs.PAT }}

    - name: Update package.json version
      uses: jossef/action-set-json-field@v2.1
      with:
        file: package.json
        field: "dependencies.rey-common"
        value: "git@github.com:REY-ID/rey-common.git#${{ inputs.VERSION || steps.latest.outputs.release }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.PAT }}
        commit-message: update rey-common version to ${{ steps.latest.outputs.release }}
        branch: upgrade/rey-common-${{ steps.latest.outputs.release }}
        delete-branch: true
        title: rey-common version ${{ steps.latest.outputs.release }}
        body: |
          This PR updates rey-common version to ${{ steps.latest.outputs.release }}
        labels: dependencies
